### ISSUE TITLE
URL verification in the proxy request

### ISSUE THREAD

**Issue by SolidWallOfCode** [yahoo/proxy-verifier#26]
I need to be able to verify the URL in the proxy request. I am testing a plugin that modifies the URL and it is insufficient to check only a field.

Currently my view is that if the URL is specified in the proxy request, it should be verified. There are two subcases -

*  The URL is used for transaction identification and is not intended to be explicitly verified. However, in this case it will always
   successfully verify because it is the transaction ID and therefore the URL in the proxy request is exactly what is in the replay file.
*  The URL is not the transaction identification. In this case, the only reason to specify it is to have it verified.

It would be of additional utility to provide some sub-URL verification options. E.g.

*  `url-scheme` : Verify only the scheme.
*  `url-path` : Verify only the path
*  `url-path-prefix` : Verify the URL path starts with this string.
*  `url-host` : Verify on the host in the URL (*not* the field!)
*  `url-query` : Verify the query string.

**Comment by bneradt** [comment]
This has been addressed  via https://github.com/yahoo/proxy-verifier/pull/53.
